apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-api-config
  namespace: fraud-detection
  labels:
    app.kubernetes.io/name: fraud-api
    app.kubernetes.io/part-of: fraud-detection-platform
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  POSTGRES_HOST: "fraud-postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "fraud_detection"
  POSTGRES_USER: "postgres"
  REDIS_HOST: "fraud-redis-service"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "fraud-kafka-service:9092"
  MODEL_NAME: "fraud_detection_xgboost"
  MODEL_VERSION: "6"
  THRESHOLD: "0.20"

